[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"

[functions."protocol"]
  timeout = 26

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
